name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: "build-and-deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.Cloudflare_Pages }}
          accountId: ${{ vars.ACCOUNT_ID}}
          command: pages deploy build --project-name=${{ vars.PROJECT_NAME }}

  upload-to-r2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Configure Rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.Rclone_Config }}" > ~/.config/rclone/rclone.conf

      - name: Upload to R2
        run: ./rclone-to-r2.sh
